
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Fri Nov 01 17:19:35 CDT 2013
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int STRLIT = 4;
  static final int rw_WHILE = 38;
  static final int rw_BOOL = 46;
  static final int LBRACKET = 11;
  static final int INCREMENT = 21;
  static final int rw_IF = 31;
  static final int SLASH = 23;
  static final int rw_CONTINUE = 33;
  static final int rw_FALSE = 36;
  static final int LPAREN = 6;
  static final int SEMI = 12;
  static final int rw_PRINT = 37;
  static final int rw_TRUE = 34;
  static final int MINUS = 28;
  static final int DECREMENT = 22;
  static final int RPAREN = 7;
  static final int NOT = 18;
  static final int rw_VOID = 44;
  static final int INTLIT = 3;
  static final int LT = 16;
  static final int rw_CONST = 43;
  static final int COMMA = 19;
  static final int rw_ELSE = 35;
  static final int GEQ = 20;
  static final int PLUS = 27;
  static final int rw_READ = 41;
  static final int rw_INT = 45;
  static final int EOF = 0;
  static final int RBRACKET = 25;
  static final int error = 1;
  static final int COR = 13;
  static final int rw_CLASS = 42;
  static final int rw_RETURN = 40;
  static final int EQ = 29;
  static final int ASG = 8;
  static final int TIMES = 17;
  static final int CHARLIT = 5;
  static final int COLON = 26;
  static final int LBRACE = 9;
  static final int rw_CHAR = 39;
  static final int RBRACE = 10;
  static final int CAND = 15;
  static final int LEQ = 24;
  static final int rw_BREAK = 32;
  static final int GT = 14;
  static final int NOTEQ = 30;
  static final int IDENTIFIER = 2;
}

